<a href="https://colab.research.google.com/github/HimanshuSharma0711/Python-Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Package:** A package is a container that contains various functions to perform specific tasks.For example, the math package includes the sqrt() function to perform the square root of a number. While working on big projects, we have to deal with a large amount of code, and writing everything together in the same file will make our code look messy. Instead, we can separate our code into multiple files by keeping the related code together in packages.Now, we can use the package whenever we need it in our projects. This way we can also reuse our code.

**Module:** In Python, we can import modules from packages using the dot (.) operator. For Example: geopy.distance, here geopy is a package whereas .distance is module of package geopy.

**Numpy:** Numpy is a package. A package is a collection of modules.

**How to import a library?**

**Syntax:** 

import numpy as np

here, **import** is a keyword, **numpy** is the package or module to be imported. **'as np'** is an alias.

The most important object defined in Numpy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero based index. Every item in an  darray takes the same size of block in the memory. Each elemment in ndarray is an object of data-type onject also called as d-type.

In [1]:
import numpy as np

#1.) One-Dimensional Array

lst = [2,3,5,7,11]
prime_array = np.array(lst)
print(prime_array) #[ 2  3  5  7 11]
print(type(prime_array)) #<class 'numpy.ndarray'>

names=['Rohit','Hitesh','Ravi']
names_array = np.array(names)
print(names_array) #['Rohit' 'Hitesh' 'Ravi']
print(type(names_array)) #<class 'numpy.ndarray'>
print(names_array.shape) #(3,)

#2.) Two - Dimensional Array

two_array = [[2,3],[3,4]]
TwoD_array = np.array(two_array)
print(TwoD_array.shape) #(2,2)

#3.) Three - Dimensional Array

three_array = [[[2,3],[3,4]],
               [[5,6],[7,8]]]
ThreeD_array = np.array(three_array)
print(ThreeD_array.shape) #(2,2,2)

#4.) Four - Dimensional Array

four_array = [
              [
               [[2,3],[3,4]],
               [[5,6],[7,8]]
                             ],
               [
                [[2,3],[3,4]],
                [[5,6],[7,8]]
                             ]
                              ]
FourD_array = np.array(four_array)
print(FourD_array.shape) #(2,2,2,2)

[ 2  3  5  7 11]
<class 'numpy.ndarray'>
['Rohit' 'Hitesh' 'Ravi']
<class 'numpy.ndarray'>
(3,)
(2, 2)
(2, 2, 2)
(2, 2, 2, 2)


**Array Inspection**

A numpy array has following attributes
1. ndarray.shape : This returns a tuple consisting of array dimensions and can be used to resized the array.
2. ndarray.ndim : Return number of dimension in an array.
3. ndarray.size : return total number of elements in array.
4. ndarray.dtype : return the datatype of an array.
5. ndarray.astype : changes datatype of an array.

In [ ]:
my_array1 = np.array([[2,3],[3,4]])
print(my_array1.shape)
print(my_array1.ndim)
print(my_array1.size)
print(my_array1.dtype)
print(my_array1.astype(float))
print(my_array1.astype(str))

my_array2=np.array([1,2.0,3,4,'abc'])
print(my_array2.dtype) #U32 - Numpy Support some more datatypes.

**Why Numpy?**

**Memory :** Numpy Data Structures takes up less space.

**Performance :** they have a need for speed and faster than lists.

**Functionality :** Scipy and Numpy have optimized functions such as linear algebra built in.

In [2]:
#Memory
import sys

s = [0,1,2,3,4,5,6,7,8,9]
print("Size of each element in this list in bytes is : ", sys.getsizeof(s))
print("Size of whole list in bytes : ", sys.getsizeof(s)*len(s))

d = np.array([0,1,2,3,4,5,6,7,8,9])
print("Size of each element in this array in bytes is : ", d.itemsize)
print("Size of whole array in bytes : ", d.size*d.itemsize)

#Performance
import time

size = 100000
list1 = range(size)
list2 = range(size)

array1 = np.arange(size)
array2= np.arange(size)

initialTime = time.time()

resultantList = [(a*b) for a,b in zip(list1,list2)]
print("time taken by list action : ", time.time() - initialTime)

initialTime = time.time()

resultantarray = array1 * array2

print("time taken by array action : ", time.time() - initialTime)

Size of each element in this list in bytes is :  152
Size of whole list in bytes :  1520
Size of each element in this array in bytes is :  8
Size of whole array in bytes :  80
time taken by list action :  0.010141372680664062
time taken by array action :  0.0007815361022949219


# **Different ways of creating an ndarray**

**Uninitialized : creating an uninitialized array of a specified shape**

In [4]:
uninitialized_array = np.empty([3,3],dtype=int)
print(uninitialized_array)


[[           29780448                   0     140564667954944]
 [ 268492805317157264     140564200478064     140564667955088]
 [5663975637200811794     140564198533680                  80]]


**Initialized : with zeros**

In [5]:
initialized_zero = np.zeros([3,3],dtype=int)
print(initialized_zero)

initialized_ones = np.ones([3,3],dtype=int)
print(initialized_ones)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**Array from numerial ranges**

**Parameters :** np.arange(start, stop, step, dtype)


In [7]:
range_array1= np.arange(1,20,2,float)
print(range_array1)

range_array2 = np.arange(10)
print(range_array2)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
[0 1 2 3 4 5 6 7 8 9]


**array full of desired value**

In [8]:
print(np.full([2,2],12))

[[12 12]
 [12 12]]


**random array**

In [9]:
print(np.random.random([2,2]))

[[0.18640158 0.88304443]
 [0.41017194 0.81050929]]


**random with range in interger**

**Parameter:** np.random.randint(start,end,[size])

In [10]:
print(np.random.randint(1,10,[3,3]))

[[7 8 9]
 [8 4 4]
 [1 3 2]]


**multiplying the array**

In [11]:
print(np.ones([3,3],dtype=int)*101)

[[101 101 101]
 [101 101 101]
 [101 101 101]]


**Identity Array**

In [12]:
print(np.identity(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Creating Ndarray with existing data**

In [13]:
#List to ndarray

lst=[1,2,3,4,5]
lstarray = np.asarray(lst)
print(lstarray)

#Tuple to ndarray

tpl = (1,2,3,4,5)
tplarray = np.asarray(tpl)
print(tplarray)

[1 2 3 4 5]
[1 2 3 4 5]


**Indexing and Slicing array**

**[start:end]** used to slice array with a gap

**[start:end:step]** used to slice array with fixed interval

In [15]:
#Slicing 1D array
D1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(D1[2:5]) #[2 3 4]
print(D1[2:9:2]) #[2 4 6 8]

#Slicing 2D array

L = [[1,2,3,4,5],[6,7,8,9,10]]
D2 = np.array(L)

print(D2[0][:3])
print(D2[1][0:4:2])

#Number of [] increases in accordance with dimension

[2 3 4]
[2 4 6 8]
[1 2 3]
[6 8]


'\nArray Manipulation\nnp.transpose(array) - to transpose array\nnp.reshape(array,shape) - to change shape of an array\nnp.resize(array,shape) - to return new array with shape\nnp.flatten(array) - to flatten the array\n'

# **Array Manipulation**

**np.transpose(array)** - to transpose array

**np.reshape(array,shape)** - to change shape of an array

**np.resize(array,shape)** - to return new array with shape

**np.flatten(array)** - to flatten the array